default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: ai_detector

test:
  <<: *default
  database: <%= ai_detector_test
